
--- ACTUALIZANDO VALORES

UPDATE TB_ARTICULO 
SET CODIGO_CA = 1
WHERE CODIGO_AR = 6;

UPDATE TB_ARTICULO
SET MARCA_AR = 'CANNON'
WHERE CODIGO_AR = 2;

UPDATE TB_ARTICULO
SET MARCA_AR = 'SAMSUNG'
WHERE CODIGO_AR IN (3, 4);