--- BORRANDO DATOS

DELETE FROM TB_ARTICULO
WHERE CODIGO_AR IN(5,6);

DELETE TB_ARTICULO
WHERE MARCA_AR = 'STANDAR';

DELETE FROM TB_MEDIDAS 
WHERE CODIGO_ME IN (3, 4);


--- CONSULTO DE DATOS

SELECT * FROM TB_ARTICULO;

SELECT * FROM TB_MEDIDAS;

SELECT CODIGO_AR,
             DESCRIPCION_AR,
             MARCA_AR
FROM TB_ARTICULO
WHERE  CODIGO_CA = 2;

SELECT *
FROM TB_ARTICULO
WHERE NOT MARCA_AR IN ('CANNON','SAMSUNG');

SELECT *
FROM TB_ARTICULO
WHERE DESCRIPCION_AR LIKE 'RE%';