
--- OPERADORES RELACIONALES

SELECT * FROM TB_NOTAS_ALUMNOS 
WHERE NOTA1 <= 15;


SELECT CODIGO_AL,
            (NOMBRE_AL || ' -  ' ||CURSO) AS NOMBRE_CURSO
FROM TB_NOTAS_ALUMNOS;

SELECT * 
FROM TB_NOTAS_ALUMNOS
WHERE  NOTA2 = 13 OR NOTA3 > 10;

SELECT *
FROM TB_NOTAS_ALUMNOS
WHERE NOT NOTA1 > 15;

INSERT INTO TB_MEDIDAS
VALUES (
        2,
        'KGS',
        'KILOGRAMOS');
        COMMIT;