---- FUNCIONES STRING

SELECT CONCAT (
        'PRUEBA PARA UTILIZAR',
        ' LA FUNCION DE CONCATENACION')
        AS PRUEBA
FROM DUAL;
--- FUNCION DE CARACTER, EN ESTE CASO EL CODIGO 65 EN ASCI REPRESENTA LA LETA A
SELECT CHR
        (89)
        AS CARACTER
FROM DUAL;

--- FUNCION PARA CAMBIAR A MAYUSCULA LA INICIAL DE CADA LETRA  
SELECT INITCAP(
        'prueba de la funcion initcap') 
        AS INICIAL_MAYUSCULA
FROM DUAL;
--- FUNCIÓN PARA CAMBIAR TODO A MAYUSCULA
SELECT UPPER(
        'prueba de la función que convierte todo el texo a mayuscula')
        AS TEXTO_MAYUSCULA
FROM DUAL;

--- FUNCIÓN PARA CAMBIAR TODO A MINISCULA
SELECT LOWER(
        'FUNCIÓN PARA CAMBIAR TODO A MINUSCULA')
        AS TEXTO_MINUSCULA
FROM DUAL;
--- FUNCIÓN AUTORELLENADO LPAD, LO UBICA DEL LADO IZQUIERDO

SELECT LPAD (
        'SAMUEL', 11, 'x') 
        AS NOMBRE
FROM DUAL;

SELECT CONCAT(
        'BOL - ',
            LPAD( '1', 4,'0' ))
        AS TICKET
FROM DUAL;

--- FUNCION RPAD, AUTORELLANADO AL LADO IZQUIERDO
SELECT RPAD(
        'DANIEL',11,'x')
        AS NOMBRE
FROM DUAL;

SELECT CONCAT(
        RPAD('P', 10, '0'), '1') 
        AS CORRELATIVO
FROM DUAL;

--- LIMPIEZA DE ESPACIOS EN BLANCO LTRIM ELIMINA ESPACIOS EN BLANCO A LA IZQUIERDA, RTRING ELIMINA ESPACIOS EN BLANCO A LA DERECHA

SELECT CONCAT(
         RTRIM('SAMUEL         '),
         LTRIM('        ALEXANDER'))
        AS NOMBRE
FROM DUAL;

--- REEMPLAZAR CONTENIDO 

SELECT REPLACE(
        'PROBANDO TEXTO DE REEMPLAZO', 'O','A')
        AS TEXTO
FROM DUAL;

--- FUNCION SUBSTR EXTRAE LOS CARACTERES QUE SE LE INDIQUE.

SELECT SUBSTR(
        'PROBANDO LA FUNCION DE EXTRAER CARACTERES',24,41 )
        AS TEXTO_EXTRAIDO
FROM DUAL;

--- CONTEO DE LA LONGITUD DEL TEXTO

SELECT LENGTH(
        'PROBANDO LA FUNCION DE CONTEO DE CARACTERES')
        AS TOTAL_CARACTERES
FROM DUAL;

--- FUNCION INSTR BUSCA LA PRIMERA INCIDENCIADE LA SUBCADENA  Y OBTIENE LA POSICION EN VALOR NUMERICO

SELECT INSTR(
        'PROBANDO FUNCION DE INSTR DE MANERA EJEMPLAR','DE')
        AS VALOR_POSICION
FROM DUAL;

--- FUNCION TRANSLATE 

SELECT TRANSLATE(
        'PROBANDO COMANDOS DE TEXTO DE REEMPLAZO','OES','035')
        AS TRANSLATE
FROM DUAL;
        
        