
--- EJECUTANDO PROCEDIMIENTO ALMACENADO CON PARÁMETRO DE SALIDA

VAR vNOTA1 NUMBER;
EXECUTE BUSCAR_NOTA_AL(4, :vNOTA1);
PRINT vNOTA1;

--- NOTA, SE DEBE SELECCIONAR TODO EL BLOQUE, PARA QUE SE EJECUTE CORRECTAMENTE.