--- CREANDO PROCEDIMIENTOS CON PARAMETRO DE ENTRADA Y DE SALIDA AL MISMO TIEMPO

CREATE PROCEDURE BUSCAR_DESCRIPCION_ME(p01 IN OUT VARCHAR2)
AS

BEGIN
    SELECT DESCRIPCION_ME
    INTO p01
    FROM TB_MEDIDAS
    WHERE ABREVIATURA_ME = p01;
END;
/