--- RELACION DE DATOS, INNER JOIN

SELECT TB_ARTICULO.CODIGO_AR,
             TB_ARTICULO.DESCRIPCION_AR,
             TB_ARTICULO.MARCA_AR,
             TB_MEDIDAS.DESCRIPCION_ME,
             TB_CATEGORIAS.DESCRIPCION_CA,
             TB_ARTICULO.STOCK_ACTUAL,
             TB_ARTICULO.FECHA_REGISTRO
FROM TB_ARTICULO
INNER JOIN TB_CATEGORIAS 
ON TB_ARTICULO.CODIGO_CA = TB_CATEGORIAS.CODIGO_CA
INNER JOIN TB_MEDIDAS
ON TB_ARTICULO.CODIGO_ME = TB_MEDIDAS.CODIGO_ME;

--- INSERCION DE DATOS LEFT JOIN TRAE LOS ELEMENTOS EN COMUN DE LA TABLA A Y B Y ADEMAS LA TOTALIDAD DE LOS COMPONENTES DE LA TABLA A
SELECT TB_CATEGORIAS.CODIGO_CA,
             TB_CATEGORIAS.DESCRIPCION_CA,
             TB_ARTICULO.DESCRIPCION_AR,
             TB_ARTICULO.MARCA_AR
FROM TB_CATEGORIAS --TABLA A
LEFT JOIN TB_ARTICULO --TABLA B
ON TB_CATEGORIAS.CODIGO_CA = TB_ARTICULO.CODIGO_CA;

--- INSERCIÓN DE DATOS RIGHT JOIN

SELECT A.CODIGO_AR,
             A.DESCRIPCION_AR,
             A.MARCA_AR,
             B.DESCRIPCION_ME
FROM TB_ARTICULO A
RIGHT JOIN TB_MEDIDAS B
ON A.CODIGO_ME = B.CODIGO_ME;