
SELECT * 
FROM TB_ARTICULO
WHERE STOCK_ACTUAL > 0 AND CODIGO_AR = 5;

UPDATE TB_ARTICULO
SET STOCK_ACTUAL = STOCK_ACTUAL + 2
WHERE MARCA_AR = 'STANDAR';

DELETE FROM TB_ARTICULO
WHERE MARCA_AR = 'STANDAR' 
OR MARCA_AR = 'HP';

DELETE FROM TB_ARTICULO
WHERE MARCA_AR IN('STANDAR','HP');

SELECT *
FROM TB_ARTICULO;