--- CREANDO FUNCION PARA EVALUAR EDAD

CREATE OR REPLACE FUNCTION F_EVALUAR_EDAD( pEDAD NUMBER )

RETURN VARCHAR2

AS
    vRETORNO VARCHAR2(50);
BEGIN
    vRETORNO := '';
    IF pEDAD < 18
    THEN vRETORNO := 'ERES MENOR DE EDAD';
    ELSE vRETORNO := 'ERES MAYOR DE EDAD';
    END IF;
    RETURN vRETORNO;

END;
/